import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./(router)/_components/Header";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Deep School | eLearning platform .",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className  }>
        {children}
       <Header />
        </body>
    </html>
  );
}
